export const metadata = {
  title: 'Terms of Service — PupilNetwork',
  description: 'Terms and conditions for using PupilNetwork.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <main className="max-w-4xl mx-auto py-24 px-4 sm:px-6">
        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100 prose prose-slate max-w-none">
          <h1 style={{ fontFamily: 'Space Grotesk, sans-serif' }}>Terms of Service</h1>
          <p className="lead">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
          
          <p>
            Welcome to PupilNetwork (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using our website and services, you agree to be bound by these Terms.
          </p>

          <h2>1. Acceptable Use</h2>
          <p>
            PupilNetwork is a platform for academic collaboration. You agree not to:
          </p>
          <ul>
            <li>Post inappropriate, offensive, or illegal content.</li>
            <li>Use the Q&amp;A board to cheat on active exams or assignments.</li>
            <li>Spam study rooms or harass other students.</li>
            <li>Attempt to bypass rate limits or premium restrictions.</li>
          </ul>

          <h2>2. Premium Subscriptions</h2>
          <p>
            Premium subscriptions are valid for 30 days from the time of activation via a premium code. 
            There are no automatic renewals. We do not offer refunds once a code has been successfully redeemed. 
            We reserve the right to revoke premium access for violations of the acceptable use policy.
          </p>

          <h2>3. AI Usage Restrictions</h2>
          <p>
            The AI Study Buddy (powered by Google Gemini) is provided to help you learn. 
            Responses are generated by AI and may occasionally be inaccurate. You should always verify important academic information.
          </p>

          <h2>4. Disclaimer</h2>
          <p>
            PupilNetwork is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. 
            As a free, student-run service, we do not guarantee 100% uptime.
          </p>

          <h2>5. Contact</h2>
          <p>
            For any questions about these Terms, email us at <a href="mailto:support@pupilnetwork.is-a.dev">support@pupilnetwork.is-a.dev</a>.
          </p>
        </div>
      </main>
    </div>
  )
}
